//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEncyclopediaService")]
    public interface IEncyclopediaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetStatus", ReplyAction="http://tempuri.org/IEncyclopediaService/GetStatusResponse")]
        bool GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetStatus", ReplyAction="http://tempuri.org/IEncyclopediaService/GetStatusResponse")]
        System.Threading.Tasks.Task<bool> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetInfo", ReplyAction="http://tempuri.org/IEncyclopediaService/GetInfoResponse")]
        L1.WcfServiceLibrary.EncyclopediaType GetInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetInfo", ReplyAction="http://tempuri.org/IEncyclopediaService/GetInfoResponse")]
        System.Threading.Tasks.Task<L1.WcfServiceLibrary.EncyclopediaType> GetInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetPart", ReplyAction="http://tempuri.org/IEncyclopediaService/GetPartResponse")]
        L1.WcfServiceLibrary.EncyclopediaPartType GetPart(string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetPart", ReplyAction="http://tempuri.org/IEncyclopediaService/GetPartResponse")]
        System.Threading.Tasks.Task<L1.WcfServiceLibrary.EncyclopediaPartType> GetPartAsync(string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetArticle", ReplyAction="http://tempuri.org/IEncyclopediaService/GetArticleResponse")]
        L1.WcfServiceLibrary.EncyclopediaArticleType GetArticle(string sPart, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetArticle", ReplyAction="http://tempuri.org/IEncyclopediaService/GetArticleResponse")]
        System.Threading.Tasks.Task<L1.WcfServiceLibrary.EncyclopediaArticleType> GetArticleAsync(string sPart, string sCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEncyclopediaServiceChannel : WindowsFormsApp1.ServiceReference1.IEncyclopediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncyclopediaServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IEncyclopediaService>, WindowsFormsApp1.ServiceReference1.IEncyclopediaService {
        
        public EncyclopediaServiceClient() {
        }
        
        public EncyclopediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncyclopediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncyclopediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncyclopediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<bool> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        public L1.WcfServiceLibrary.EncyclopediaType GetInfo() {
            return base.Channel.GetInfo();
        }
        
        public System.Threading.Tasks.Task<L1.WcfServiceLibrary.EncyclopediaType> GetInfoAsync() {
            return base.Channel.GetInfoAsync();
        }
        
        public L1.WcfServiceLibrary.EncyclopediaPartType GetPart(string sCode) {
            return base.Channel.GetPart(sCode);
        }
        
        public System.Threading.Tasks.Task<L1.WcfServiceLibrary.EncyclopediaPartType> GetPartAsync(string sCode) {
            return base.Channel.GetPartAsync(sCode);
        }
        
        public L1.WcfServiceLibrary.EncyclopediaArticleType GetArticle(string sPart, string sCode) {
            return base.Channel.GetArticle(sPart, sCode);
        }
        
        public System.Threading.Tasks.Task<L1.WcfServiceLibrary.EncyclopediaArticleType> GetArticleAsync(string sPart, string sCode) {
            return base.Channel.GetArticleAsync(sPart, sCode);
        }
    }
}
